[build]
  command = """
    npm install && 
    npm run bootstrap && 
    npm run build:one components && 
    npm run build:one trader
  """
  publish = "packages/trader/build"  # Changed to point to build folder
  environment = { 
    NODE_VERSION = "16.16.0",
    CI = "false",
    NODE_OPTIONS = "--max_old_space_size=4096"
  }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"