[build]
  command = "npm run bootstrap && npm run build:one trader"
  publish = "dist/packages/trader/dist"
  environment = { NODE_VERSION = "20.19.1" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
